-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 15:49:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ALUNOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALUNOS` (
  `idALUNOS` INT NOT NULL,
  `PRIMEIRO_NOME` VARCHAR(45) NOT NULL,
  `SOBRENOME` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `DATA_NASCIMENTO` VARCHAR(45) NOT NULL,
  `ENDEREÇO` VARCHAR(45) NOT NULL,
  `MATRICULAS_MATRICULAS` INT NOT NULL,
  PRIMARY KEY (`idALUNOS`),
  INDEX `fk_ALUNOS_MATRICULAS2_idx` (`MATRICULAS_MATRICULAS` ASC) VISIBLE,
  CONSTRAINT `fk_ALUNOS_MATRICULAS2`
    FOREIGN KEY (`MATRICULAS_MATRICULAS`)
    REFERENCES `mydb`.`MATRICULAS` (`MATRICULAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BAIRROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BAIRROS` (
  `BAIRROS` INT NOT NULL,
  `SENAC - SEPETIBA` VARCHAR(45) NOT NULL,
  `SENAC - SANTA CRUZ` VARCHAR(45) NOT NULL,
  `SENAC - CAMPO GRANDE` VARCHAR(45) NOT NULL,
  `HOME OFFICE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BAIRROS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TURMA` (
  `TURMA` INT NOT NULL,
  `MANHÃ` VARCHAR(45) NOT NULL,
  `TARDE` VARCHAR(45) NOT NULL,
  `NOITE` VARCHAR(45) NOT NULL,
  `ALUNOS_idALUNOS` INT NOT NULL,
  `LOCAIS_idLOCAIS` INT NOT NULL,
  INDEX `fk_TURMA_ALUNOS1_idx` (`ALUNOS_idALUNOS` ASC) VISIBLE,
  INDEX `fk_TURMA_LOCAIS1_idx` (`LOCAIS_idLOCAIS` ASC) VISIBLE,
  PRIMARY KEY (`TURMA`),
  CONSTRAINT `fk_TURMA_ALUNOS1`
    FOREIGN KEY (`ALUNOS_idALUNOS`)
    REFERENCES `mydb`.`ALUNOS` (`idALUNOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TURMA_LOCAIS1`
    FOREIGN KEY (`LOCAIS_idLOCAIS`)
    REFERENCES `mydb`.`BAIRROS` (`BAIRROS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MATRICULAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MATRICULAS` (
  `MATRICULAS` INT NOT NULL,
  `DATA MATRICULA` VARCHAR(45) NOT NULL,
  `TOTAL DE MATRICULA` VARCHAR(45) NOT NULL,
  `TURMA_TURMA` INT NOT NULL,
  PRIMARY KEY (`MATRICULAS`),
  INDEX `fk_MATRICULAS_TURMA1_idx` (`TURMA_TURMA` ASC) VISIBLE,
  CONSTRAINT `fk_MATRICULAS_TURMA1`
    FOREIGN KEY (`TURMA_TURMA`)
    REFERENCES `mydb`.`TURMA` (`TURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CURSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURSOS` (
  `idCURSOS` INT NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `PREÇO` VARCHAR(45) NOT NULL,
  `DATA DE INICIO` VARCHAR(45) NOT NULL,
  `DATA DE TERMINO` VARCHAR(45) NOT NULL,
  `CARGA HORARIA` VARCHAR(45) NOT NULL,
  `TURMA_idTURMA` INT NOT NULL,
  `LOCAIS_idLOCAIS` INT NOT NULL,
  PRIMARY KEY (`idCURSOS`),
  INDEX `fk_CURSOS_TURMA1_idx` (`TURMA_idTURMA` ASC) VISIBLE,
  INDEX `fk_CURSOS_LOCAIS1_idx` (`LOCAIS_idLOCAIS` ASC) VISIBLE,
  CONSTRAINT `fk_CURSOS_TURMA1`
    FOREIGN KEY (`TURMA_idTURMA`)
    REFERENCES `mydb`.`TURMA` (`TURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSOS_LOCAIS1`
    FOREIGN KEY (`LOCAIS_idLOCAIS`)
    REFERENCES `mydb`.`BAIRROS` (`BAIRROS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matérias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matérias` (
  `Matérias` INT NOT NULL,
  `FOFT` VARCHAR(45) NOT NULL,
  `HARD` VARCHAR(45) NOT NULL,
  `CURSOS_idCURSOS` INT NOT NULL,
  `ALUNOS_idALUNOS` INT NOT NULL,
  PRIMARY KEY (`Matérias`),
  INDEX `fk_Matérias_CURSOS1_idx` (`CURSOS_idCURSOS` ASC) VISIBLE,
  INDEX `fk_Matérias_ALUNOS1_idx` (`ALUNOS_idALUNOS` ASC) VISIBLE,
  CONSTRAINT `fk_Matérias_CURSOS1`
    FOREIGN KEY (`CURSOS_idCURSOS`)
    REFERENCES `mydb`.`CURSOS` (`idCURSOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matérias_ALUNOS1`
    FOREIGN KEY (`ALUNOS_idALUNOS`)
    REFERENCES `mydb`.`ALUNOS` (`idALUNOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TURMA_has_ALUNOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TURMA_has_ALUNOS` (
  `TURMA_TURMA` INT NOT NULL,
  `ALUNOS_idALUNOS` INT NOT NULL,
  PRIMARY KEY (`TURMA_TURMA`, `ALUNOS_idALUNOS`),
  INDEX `fk_TURMA_has_ALUNOS_ALUNOS1_idx` (`ALUNOS_idALUNOS` ASC) VISIBLE,
  INDEX `fk_TURMA_has_ALUNOS_TURMA1_idx` (`TURMA_TURMA` ASC) VISIBLE,
  CONSTRAINT `fk_TURMA_has_ALUNOS_TURMA1`
    FOREIGN KEY (`TURMA_TURMA`)
    REFERENCES `mydb`.`TURMA` (`TURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TURMA_has_ALUNOS_ALUNOS1`
    FOREIGN KEY (`ALUNOS_idALUNOS`)
    REFERENCES `mydb`.`ALUNOS` (`idALUNOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matérias_has_CURSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matérias_has_CURSOS` (
  `Matérias_Matérias` INT NOT NULL,
  `CURSOS_idCURSOS` INT NOT NULL,
  PRIMARY KEY (`Matérias_Matérias`, `CURSOS_idCURSOS`),
  INDEX `fk_Matérias_has_CURSOS_CURSOS1_idx` (`CURSOS_idCURSOS` ASC) VISIBLE,
  INDEX `fk_Matérias_has_CURSOS_Matérias1_idx` (`Matérias_Matérias` ASC) VISIBLE,
  CONSTRAINT `fk_Matérias_has_CURSOS_Matérias1`
    FOREIGN KEY (`Matérias_Matérias`)
    REFERENCES `mydb`.`Matérias` (`Matérias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matérias_has_CURSOS_CURSOS1`
    FOREIGN KEY (`CURSOS_idCURSOS`)
    REFERENCES `mydb`.`CURSOS` (`idCURSOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
